# .terraform-docs.yml
content: |-
  <p align="center">
    <a href="https://github.com/carlosrfjunior/terraform-modules">
      <image src="https://raw.githubusercontent.com/carlosrfjunior/carlosrfjunior/main/assets/gopher-iron-man-flying.png" style="width: 300px;">
    </a>
  </p>

  {{ .Header }}

  ## Full example implementation

  ### Variable
    ```hcl
  {{ include "example/variables.tf" }}
  ```

  ### Provider
  ```hcl
  {{ include "example/providers.tf" }}
  ```

  ### Tagging
  ```hcl
  {{ include "example/main.tf" }}
  ```


  ### Main
  ```hcl
  {{ include "example/main.tf" }}
  ```

  {{ .Providers }}
  {{ .Requirements }}
  {{ .Resources }}
  {{ .Inputs }}
  {{ .Modules }}
  {{ .Outputs }}
  {{ .Footer }}
