# .terraform-docs.yml
content: |-
  <p align="center">
    <a href="https://github.com/carlosrfjunior/helm-charts">
      <image src="../assets/hotmart-logo.png" style="width: 300px;">
    </a>
  </p>

  {{ .Header }}

  ## Full example implementation

  ### Variable
    ```hcl
  {{ include "example/variables.tf" }}
  ```

  ### Provider
  ```hcl
  {{ include "example/providers.tf" }}
  ```

  ### Tagging
  ```hcl
  {{ include "example/tagging.tf" }}
  ```


  ### Main
  ```hcl
  {{ include "example/main.tf" }}
  ```

  {{ .Inputs }}

  {{ .Outputs }}
