server:
  env:
    - name: EXTRA_PIP_PACKAGES
      value: >-
        -U prefect-github prefect-databricks prefect-slack prefect-aws controlflow
  # image:
  #   prefectTag: 3.0.0rc19-python3.11-kubernetes
    # repository: prefecthq/prefect
postgresql:
  enabled: true
  image:
    tag: 16.4.0
