# .terraform-docs.yml
content: |-
  <p align="center">
    <a href="https://github.com/carlosrfjunior/terraform-modules">
      <image src="https://avatars.githubusercontent.com/u/180111812?s=400&u=cda6d53ade890c5d47426504081e4fcb1167199d&v=4" style="width: 300px;">
    </a>
  </p>

  {{ .Header }}

  > [!TIP]
  > At the end of this file you can see a basic example of how to use the module.

  ## Documentations:
  - [Custom Networking](./docs/custom-networking.md)
  - [AWS EKS Add-ons](./docs/aws-eks-addons.md)
  - [ArgoCD Applications](./docs/argocd-apps.md)


  {{ .Providers }}
  {{ .Requirements }}
  {{ .Resources }}
  {{ .Inputs }}
  {{ .Modules }}
  {{ .Outputs }}
  {{ .Footer }}

  ## Full example implementation
  ### AWS EKS Module - Example
  `Source Reference File:` [example/main.tf](example/main.tf)
  ```hcl
  {{ include "example/main.tf" }}
  ```
